### ISSUE TITLE
Is it possible to create conference call with this module?

### ISSUE THREAD

**Issue by kushaldias** [hoxfon/react-native-twilio-programmable-voice#101]
I need to know whether it is possible to make conference call app with this library?

**Comment by liemdo** [comment]
Basically yes but you have to talk to Twilio support on how to implement the back end.

**Comment by BilalPasta** [comment]
> end

for conference call did we need to upgrade sdk?

**Comment by jdegger** [comment]
Yes this possible. You basically make sure that your back-end application handles this on the outgoing call. It is outside the scope of this repo to have any additional features for conference calling as it's back-end configuration.

since a long time has passed I will be closing this issue. Read our repository update in #158.
