### ISSUE TITLE
Add CallKit performPlayDTMFCallAction

### ISSUE THREAD

**Issue by eabait** [hoxfon/react-native-twilio-programmable-voice#23]
The method `provider:performPlayDTMFCallAction` is called when the provider performs the specified play DTMF call action.
Adding this method would allow us to catch Callkit's keypad. I've been testing the following implementation:

```
- (void)provider:(CXProvider *)provider performPlayDTMFCallAction:(CXPlayDTMFCallAction *)action {
  if (self.call && self.call.state == TVOCallStateConnected) {
    RCTLogInfo(@"SendDigits %@", action.digits);
    [self.call sendDigits:action.digits];
  }
}
```

What do you think?
Cheers
Esteban

**Comment by fabriziomoscon** [comment]
Hi @eabait,
I saw your interaction on the Obj-C repo! Nice to see your using RN! Let me know how it goes.
Most of the code I use in here is copied by Twilio's quickstart repo. Would this improvement benefit this repo or also the Twilio's one? If the later, I encourage you to also report it there.

I am not using DTMF tones in my app yet, so it is completely possible that the method is even broken :)
I would be very happy to accept pull request to fix this and other issues on ios. I am not really an ios developer you know ;)

Thanks for reporting!

**Comment by fabriziomoscon** [comment]
@eabait I noticed in iOS 11 that incoming calls trigger the iOS call app for answering the call, but then the focus is passed into the react-native app. Can you confirm this happens in your app as well?
If that stands your code, although correct, will not be called, because the DTMF will be passed from Javascript.

**Comment by eabait** [comment]
Hey Fabrizio

I didnt get the notification of your answer, hence my delayed response. 
We have our app already in prod, and users are responding to an automatic call we send using Twilio with DTMF tones. So, to answer your question, the code I passed still stands, even with iOS 11.
However, we are using a fork of your library with that change, and a dependency on Twilio SDK older than the latest version of this lib.

**Comment by nipun0505** [comment]
@eabait I am implementing the same in my app. Just wanted to confirm that if an app makes a VOIP call to an IVR where it says enter your phone number after this beep. The digits tapped on the keypad will be passed to the delegate method of my app correct?

And this is only possible via a VOIP call because we can't tap/interrupt a normal phone call triggered with the URL scheme right?

**Comment by jdegger** [comment]
This issue is added to the backlog, which will be picked up after our 1st priority work is done. Read our repository update in #158.

**Comment by fabriziomoscon** [comment]
v4.1.0
