### ISSUE TITLE
differences between iOS and Android callbacks data

### ISSUE THREAD

**Issue by noamSoluto** [hoxfon/react-native-twilio-programmable-voice#37]
Hi,
I have notice that there're differences between iOS and Android callbacks data, for example:
- iOS has 'to' and 'from' attributes in the connectionDidConnect event data instead of 'call_to' and 'call_from'
- Android doesn't have the 'call_from' and 'call_to' in the connectionDidConnect event data
- Android has a deviceDidReceiveIncoming event and iOS doesn't
- iOS has a callRejected event and Android doesn't

is there any reason for those differences or I can add/fix them?  

best regards,
Noam 

Please include following information for better support

What version of React Native are you running? 
0.46.3
What version of react-native-twilio-programmable-voice are you running? 
2.8.0
What device are you using? (e.g iOS9 simulator, Android 6 device)?
iPhone 6/ Samsung S8
Is your app running in foreground, background or not running?
foreground
Is there any relevant message in the log?
If using iOS, which pod version are you using?
1.3.1

**Comment by fabriziomoscon** [comment]
@noamSoluto you are right!
> iOS has 'to' and 'from' attributes in the connectionDidConnect event data instead of 'call_to' and 'call_from'
I can fix this
> Android doesn't have the 'call_from' and 'call_to' in the connectionDidConnect event data
they seem to be missing for 1 of the 2 events
> Android has a deviceDidReceiveIncoming event and iOS doesn't
because CallKit handles it without sending an event - as far as I know
> iOS has a callRejected event and Android doesn't
because CallKit handles it without sending an event - as far as I know

For the first 2 point I will need to open a PR, if you want to try, please be my guest.

**Comment by fabriziomoscon** [comment]
@noamSoluto 
Errata corrige
> Android has a deviceDidReceiveIncoming event and iOS doesn't

also iOS has the event `deviceDidReceiveIncoming`, I corrected the README

> iOS has a callRejected event and Android doesn't

on Android there is a reject() API because the UI is provided by your app, whereas on iOS CallKit handles the UI and the reject button. In this sense the reject event notify your app when the CAllKit screen reject button is pressed.

**Comment by fabriziomoscon** [comment]
@noamSoluto I have addressed your first two points in version `3.0.0`

> iOS has 'to' and 'from' attributes in the connectionDidConnect event data instead of 'call_to' and 'call_from'

> Android doesn't have the 'call_from' and 'call_to' in the connectionDidConnect event data

**Comment by noamSoluto** [comment]
@fabriziomoscon thanks for your help, I will try the latest version
