### ISSUE TITLE
Android - implement setRegion

### ISSUE THREAD

**Issue by fabriziomoscon** [hoxfon/react-native-twilio-programmable-voice#39]
Android Twilio Voice SDK beta 17 has a new feature called Regions
references:

https://www.twilio.com/docs/api/voice-sdk/android/changelog#200-beta17
https://www.twilio.com/docs/api/voice-sdk/regions

I have asked Twilio clarification on how to use best this new API.

**Comment by jdegger** [comment]
We sometimes encounter problems when our app runs behind:
- Mobile device management
- Custom APN
- Firewalled WiFi

I suppose I'm not the only one who has noticed these limits. The IP-ranges for all regions should be whitelisted by the firewall in order to get it to work.

The list of IPs is huge: https://www.twilio.com/docs/voice/client/regions

Forcing the connection through one region, makes the list of IPs which should be whitelisted smaller. This can be done in the TwilioVoice SDK according to the docs here: https://www.twilio.com/docs/voice/voip-sdk/regions

When the new SDK version lands, it might be interesting to consider implementing `setRegion()`.

Let me know what your thoughts are.

**Comment by fmonsalvo** [comment]
@jdegger @fabriziomoscon I believe we could have a set of constants referencing each of the new "edges" and allow users to set them using `Voice.setEdge("ashburn-ix");` on android and `TwilioVoice.edge = "ashburn-ix";` on iOS.
Something like what we have for connection status.
What do you think?

**Comment by jdegger** [comment]
Maybe just send the string value to setEdge/setRegion instead of adding the edges as contants, otherwise we would have to update our package for every new edge Twilio adds, right?

**Comment by fmonsalvo** [comment]
Yes, that sounds just right. I'll try to send a PR later today with this.

**Comment by fmonsalvo** [comment]
@jdegger sorry for my late reply, I've been using setEdge on iOS for a while locally so I moved on to implement it on android.
There's one catch anyway, since Android SDK uses setRegion till version 5.3.0 and setEdge from there on.
Should we implement the deprecated setRegion method or should we upgrade Android SDK to version 5.6.0 (Latest at the time of writing)?

**Comment by jdegger** [comment]
@fmonsalvo I think we should wait for @fabriziomoscon to finish his PR maybe? I think he chose 5.0.1 because he is updating step by step from the twilio docs.

I will discuss with him also.

**Comment by jdegger** [comment]
ps: thanks for your efforts, highly appreciated!

**Comment by fmonsalvo** [comment]
Yes, let's wait for that PR to be merged and then I'll send mine.
I'll look into the other items in the backlog and see which one I can work on.

**Comment by fabriziomoscon** [comment]
This is superseded by https://www.twilio.com/docs/voice/voip-sdk/android/3x-changelog#530
