### ISSUE TITLE
Framework not found TwilioVoice

### ISSUE THREAD

**Issue by nxz91** [hoxfon/react-native-twilio-programmable-voice#83]
Did you follow all the instructions as specified in the Twilio Quickstart repositories?
Actually I didn't get this far
What version of React Native are you running?
0.52.0
What version of react-native-twilio-programmable-voice are you running?
3.18.0
What device are you using? (e.g iOS10 simulator, Android 7 device)?
iPhone 6s
Is your app running in foreground, background or not running?
Not running
Is there any relevant message in the log?
When trying to build, the build fails with "Framework not found TwilioVoice"

If using iOS, which pod version are you using?
Cocoapods 1.5.0, pod 'TwilioVoice', '~> 2.0.0'

Step to reproduce
1. yarn add react-native-programmable-voice
2. react-native link react-native-programmable-voice
3. pod init
4. Edited Podfile like so:
```source 'https://github.com/cocoapods/specs'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'yotribe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for yotribe
  pod 'TwilioVoice', '~> 2.0.0'
  pod 'RNTwilioVoice', path: '../node_modules/react-native-twilio-programmable-voice'
  target 'yotribeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end```

5. Tried to run app on iPhone
6. Build failed with said error

Any ideas?

Thanks!
Leonard

**Comment by jheyer159** [comment]
I ran into this issue before and it has to do with Xcode not initializing the TwilioVoice framework correctly. There was no one task that fixed it for me, but some things that did eventually work for me was running ‘pod deintegrate’ with Xcode closed, then pod init to rebuild the pods folder. 

I’ve literally seen this error popup on one build, restart Xcode, then it will go away. Assuming everything is connected up correctly then TwilioVoice should be linked. 

I even had success with changing the order, dragging and dropping, of the linked frameworks in Xcode. 

You also want to be opening the .xcworkspace folder in Xcode to make sure your pods are being recognized. 

I also tried setting the pods file build for TwilioVoice to be an exact version using = instead of ~>

I know that error is frustrating, and you can thank Xcode for that.

**Comment by nxz91** [comment]
Thank you! I finally could build after creating an app using react-native init from scratch and moving all resources back in there.
